// Code generated by protoc-gen-go. DO NOT EDIT.
// source: binbin.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type BinBinRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BinBinRequest) Reset()         { *m = BinBinRequest{} }
func (m *BinBinRequest) String() string { return proto.CompactTextString(m) }
func (*BinBinRequest) ProtoMessage()    {}
func (*BinBinRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_79d94cfc5a619fa3, []int{0}
}

func (m *BinBinRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BinBinRequest.Unmarshal(m, b)
}
func (m *BinBinRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BinBinRequest.Marshal(b, m, deterministic)
}
func (m *BinBinRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BinBinRequest.Merge(m, src)
}
func (m *BinBinRequest) XXX_Size() int {
	return xxx_messageInfo_BinBinRequest.Size(m)
}
func (m *BinBinRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BinBinRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BinBinRequest proto.InternalMessageInfo

func (m *BinBinRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type BinBinReply struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BinBinReply) Reset()         { *m = BinBinReply{} }
func (m *BinBinReply) String() string { return proto.CompactTextString(m) }
func (*BinBinReply) ProtoMessage()    {}
func (*BinBinReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_79d94cfc5a619fa3, []int{1}
}

func (m *BinBinReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BinBinReply.Unmarshal(m, b)
}
func (m *BinBinReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BinBinReply.Marshal(b, m, deterministic)
}
func (m *BinBinReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BinBinReply.Merge(m, src)
}
func (m *BinBinReply) XXX_Size() int {
	return xxx_messageInfo_BinBinReply.Size(m)
}
func (m *BinBinReply) XXX_DiscardUnknown() {
	xxx_messageInfo_BinBinReply.DiscardUnknown(m)
}

var xxx_messageInfo_BinBinReply proto.InternalMessageInfo

func (m *BinBinReply) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*BinBinRequest)(nil), "proto.BinBinRequest")
	proto.RegisterType((*BinBinReply)(nil), "proto.BinBinReply")
}

func init() { proto.RegisterFile("binbin.proto", fileDescriptor_79d94cfc5a619fa3) }

var fileDescriptor_79d94cfc5a619fa3 = []byte{
	// 134 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x49, 0xca, 0xcc, 0x4b,
	0xca, 0xcc, 0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05, 0x53, 0x4a, 0xca, 0x5c, 0xbc,
	0x4e, 0x99, 0x79, 0x4e, 0x99, 0x79, 0x41, 0xa9, 0x85, 0xa5, 0xa9, 0xc5, 0x25, 0x42, 0x42, 0x5c,
	0x2c, 0x79, 0x89, 0xb9, 0xa9, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x60, 0xb6, 0x92, 0x3a,
	0x17, 0x37, 0x4c, 0x51, 0x41, 0x4e, 0xa5, 0x90, 0x04, 0x17, 0x7b, 0x6e, 0x6a, 0x71, 0x71, 0x62,
	0x3a, 0x4c, 0x15, 0x8c, 0x6b, 0x64, 0xcb, 0xc5, 0x06, 0x51, 0x28, 0x64, 0xcc, 0xc5, 0x1a, 0x9c,
	0x58, 0xe9, 0x91, 0x29, 0x24, 0x02, 0xb1, 0x4f, 0x0f, 0xc5, 0x16, 0x29, 0x21, 0x34, 0xd1, 0x82,
	0x9c, 0x4a, 0x25, 0x86, 0x24, 0x36, 0xb0, 0xa0, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0x6c, 0xfb,
	0xd6, 0xe4, 0xaa, 0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// BinBinClient is the client API for BinBin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BinBinClient interface {
	SayHi(ctx context.Context, in *BinBinRequest, opts ...grpc.CallOption) (*BinBinReply, error)
}

type binBinClient struct {
	cc *grpc.ClientConn
}

func NewBinBinClient(cc *grpc.ClientConn) BinBinClient {
	return &binBinClient{cc}
}

func (c *binBinClient) SayHi(ctx context.Context, in *BinBinRequest, opts ...grpc.CallOption) (*BinBinReply, error) {
	out := new(BinBinReply)
	err := c.cc.Invoke(ctx, "/proto.BinBin/SayHi", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BinBinServer is the server API for BinBin service.
type BinBinServer interface {
	SayHi(context.Context, *BinBinRequest) (*BinBinReply, error)
}

func RegisterBinBinServer(s *grpc.Server, srv BinBinServer) {
	s.RegisterService(&_BinBin_serviceDesc, srv)
}

func _BinBin_SayHi_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BinBinRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BinBinServer).SayHi(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.BinBin/SayHi",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BinBinServer).SayHi(ctx, req.(*BinBinRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _BinBin_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.BinBin",
	HandlerType: (*BinBinServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHi",
			Handler:    _BinBin_SayHi_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "binbin.proto",
}
